const resources = {
  1: [
    require("../images/game1/bonus.png"),
    require("../images/game1/objects/o1.png"),
    require("../images/game1/objects/o2.png"),
    require("../images/game1/objects/o3.png"),
    require("../images/game1/objects/o4.png"),
    require("../images/game1/objects/o5.png"),
    require("../images/game1/objects/o6.png"),
  ],
  2: [
    require("../images/game2/bonus.png"),
    require("../images/game2/bg.png"),
    require("../images/game2/objects/o1.png"),
    require("../images/game2/objects/o2.png"),
    require("../images/game2/objects/o3.png"),
    require("../images/game2/objects/o4.png"),
    require("../images/game2/objects/o5.png"),
  ],
  3: [
    require("../images/game3/bonus.png"),
    require("../images/game3/bg.png"),
    require("../images/game3/objects/o1.png"),
    require("../images/game3/objects/o2.png"),
    require("../images/game3/objects/o3.png"),
    require("../images/game3/objects/o4.png"),
    require("../images/game3/objects/o5.png"),
    require("../images/game3/objects/o6.png"),
    require("../images/game3/objects/o7.png"),
    require("../images/game3/objects/o8.png"),
  ],
  4: [
    require("../images/game4/bottom1.png"),
    require("../images/game4/bottom2.png"),
    require("../images/game4/bottom3.png"),
    require("../images/game4/bottom4.png"),
    require("../images/game4/can.png"),
    require("../images/game4/cap.png"),
    require("../images/game4/circles.png"),
    require("../images/game4/flame.png"),
    require("../images/game4/glasses.png"),
    require("../images/game4/guitar.png"),
    require("../images/game4/plan1.png"),
    require("../images/game4/plan2.png"),
    require("../images/game4/plan3.png"),
    require("../images/game4/top1.png"),
    require("../images/game4/top2.png"),
    require("../images/game4/top3.png"),
    require("../images/game4/top4.png"),
  ],
  5: [require("../images/game5/scene.png")],
};

export default resources;
